### ISSUE TITLE
Auto-refresh files cache periodically

### ISSUE THREAD

**Issue by jgierer12** [vim-ctrlspace/vim-ctrlspace#214]
Hi, is it possible to bust the file-list cache periodically? It is really annoying when I can't open a file because I forgot to refresh the cache after adding or moving a file. Alternatively, could you implement an option to completely disable caching? I would take that over the current behavior, especially since `ag` is almost instant in medium-sized projects anyways.

**Comment by cometsong** [comment]
To clarify: do you mean there is a non-existent buffer in the file-list?

Issues with that idea are buffers for which files have been deleted, or are no longer accessible because on a network drive or mount that will be back later (eg sometimes I work on my laptop and have some remote files open, keeping them open for reference on my locally modified files).

**Comment by jgierer12** [comment]
Oops, sorry for responding so late, this kind of flew under my radar.

First off, I don't really use Vim anymore as I switched back to VSCode. But what I meant was that when I deleted a file, it would still show up in the CtrlSpace file list.
