### ISSUE TITLE
Is that possible put all cs_files, cs_workspace & cs_cache in the same folder?

### ISSUE THREAD

**Issue by markwu** [vim-ctrlspace/vim-ctrlspace#42]
Currently, I can customize the cache_dir (according to the document), and force .cs_cache saved in my preferred folder like ~/.vim/cache/ctrlspace.

Is that possible support this for cs_files and cs_workspace, too? 

Therefore I can have them all in the same folder instead of in repository itself, and easier for management.

Mark

**Comment by eyalk11** [comment]
Added related pull request . 

https://github.com/vim-ctrlspace/vim-ctrlspace/pull/320

It is very problematic it is to put random files in project code you work on . Sometimes they are even on share or a new computer. 

I don't understand why a person wouldn't want quick access to all its workspaces instead of them being spread across folders he doesn't even remember probably.
