### ISSUE TITLE
Recently opened files

### ISSUE THREAD

**Issue by rgrinberg** [vim-ctrlspace/vim-ctrlspace#95]
Would be great to search these using ctrlspace as well. You could maybe even reuse https://github.com/Shougo/neomru.vim

**Comment by zaferot** [comment]
+1

**Comment by KoFish** [comment]
Personally the lack of support for MRU is starting to make it really not worth it for me to continue using ctrlspace. Especially due to the idea of having modal navigation of the menu since this makes me need to first scan the entire list of results, decide if the file I'm looking for is there, and if there is too many files I need to enter search mode to make sure, otherwise I need to either open the file (`e<path-to-file`) or `O` to search in all the project files. This is, of course, not a problem when I'm just switching between to files due to the `C-6` key binding in vim but as soon as I need to rotate between more than two files I really would like to get some help from CtrlSpace :)

Btw, if I knew any vimscript I would gladly help out with this myself but I assume that it would take longer for me to get a grasp of the language and the code of ctrlspace than it would for someone who already who already at least knows the language.
